// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDSSCNlzDzTwDH3-MvrGoeNzZIATzM058',
    appId: '1:542928930814:web:8798f44b3e32bc0f74e2af',
    messagingSenderId: '542928930814',
    projectId: 'ott-platform-18448',
    authDomain: 'ott-platform-18448.firebaseapp.com',
    storageBucket: 'ott-platform-18448.appspot.com',
    measurementId: 'G-DP7E0SVWGR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoemWQxwbYne1jUUqawnxCuf7vcO1iF14',
    appId: '1:542928930814:android:544311fff84adb1e74e2af',
    messagingSenderId: '542928930814',
    projectId: 'ott-platform-18448',
    storageBucket: 'ott-platform-18448.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGc48tjJ-h90Q-HFUIXfDxpjCF1ly0Lus',
    appId: '1:542928930814:ios:903171fb4e23cedb74e2af',
    messagingSenderId: '542928930814',
    projectId: 'ott-platform-18448',
    storageBucket: 'ott-platform-18448.appspot.com',
    iosBundleId: 'com.example.ottApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGc48tjJ-h90Q-HFUIXfDxpjCF1ly0Lus',
    appId: '1:542928930814:ios:16f36ff39af9ddfd74e2af',
    messagingSenderId: '542928930814',
    projectId: 'ott-platform-18448',
    storageBucket: 'ott-platform-18448.appspot.com',
    iosBundleId: 'com.example.ottApp.RunnerTests',
  );
}
